config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: "welcome#index", as: 'root'
  get '/users/login', to: "user_sessions#new", as: 'users_login'
  post '/users/login', to: "user_sessions#create"
  get '/vendors/login', to: 'vendor_sessions#new', as: 'vendors_login'
  post '/vendors/login', to: 'vendor_sessions#create'
  delete '/users/logout', to: 'user_sessions#destroy', as: 'users_logout'
  delete '/vendors/logout', to: 'vendor_sessions#destroy', as: 'vendors_logout'
  get '/vendors/:id/gigs', to: 'vendors#gigs', as: 'vendor_gigs'
  get '/vendors/:id/responses', to: 'vendors#responses', as: 'vendor_responses'

  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/vendors/:id/reviews', to: 'vendors#reviews', as: 'vendor_reviews'
  get '/posts/:id/messages', to: 'posts#messages', as: 'message'
  get '/index', to: 'searches#index', as: 'index_search'
  get '/search', to: 'searches#new', as: 'new_search'
  get '/show_search', to: 'searches#show_search', as: 'show_searches'
  post '/search', to: 'searches#create'
  post '/vendors/:id/add_service', to: 'vendors#add_service', as: 'add_service'

  get '/search', to: 'searches#new', as: "search_new"

  resources :responses, only: [:new,:create,:destroy]
  resources :users, :vendors, :posts, :reviews
  resources :messages, only: [:create]
  resources :searches, only: [:show, :show_search, :create]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  first_name      :string
#  last_name       :string
#  street_address  :string
#  city            :string
#  state           :string
#  zip_code        :integer
#  email           :string
#  phone           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :reviews
  has_many :responses, through: :posts
  has_many :sessions

  before_validation :password_criteria
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "is invalid" }
  validates :username, uniqueness: true

  def password_criteria
    if self.password_digest.nil?
      errors.add(:password, "is invalid") if !(password.length > 6 && password =~ /[A-Z]/ && password =~ /[0-9]/ && password != username)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_logged_in?, only: [:show, :index]
  before_action :users_page?, :user_exists?, only: [:show]

  def index
    redirect_to user_path(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def show
    #should we do current_user in the find so it always goes to his page? Or leave it as params and check whether its his page
    @user = User.find(params[:id])
  end

  def posts
    @posts = User.find(current_user).posts
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :street_address, :city, :state, :zip_code, :email, :phone)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_table.html.erb
<table>
<thead>
  <tr>
      <th>User</th>
      <th>Title</th>
      <th>Due On</th>
  </tr>
</thead>
<tbody>
  <% @user.posts.each do |gig| %>
  <!-- <p>User: <%= gig.user.username %></p>
  <p>Title: <%= gig.title %></p>
  <p>Description <%= gig.description %></p> -->
    <tr>
      <td> <%= gig.user.username %> </td>
      <td> <%= link_to "#{gig.title}", post_path(gig), method: 'get' %> </td>
      <td> <%= gig.created_at%> </td>
    </tr>
  <!-- add button that allows user and vendor to go to show page of message controller and then allows to message -->
  <% end %>

</tbody>
</table>
<% if !@user.posts.empty? %>
<div class="waves-effect waves-light btn", style="float:right"> <%= button_to "All Active Posts", user_posts_path, method: 'get' %> </div>
<% else %>
<div class="waves-effect waves-light btn", style="float:right"> No Active Posts </div>
<% end %>
<br>

app/views/users/edit.html.erb
<div align="center"><h2>Edit Your Profile:</h2></div><br><br>


<div class="container">

  <%= form_for @user do |f| %>
  <div class="input-field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br>
  </div>

  <div class="input-field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
  </div>

  <div class="input-field">
  <%= f.label :street_address %>
  <%= f.text_field :street_address %><br>
  </div>

  <div class="input-field">
  <%= f.label :city %>
  <%= f.text_field :city %><br>
  </div>

  <div class="input-field">
    <%= f.label :state %>
    <%= f.text_field :state %><br>
  </div>

  <div class="input-field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %><br>
  </div>

  <div class="input-field">
    <%= f.label :phone %>
    <%= f.text_field :phone %><br><br>
  </div>

  <center><div>
    <%= f.submit "Update Profile", class: "waves-effect waves-light btn"%>
    <%= button_to "Cancel", user_path, method: 'get', class: "waves-effect waves-light btn" %>
  </div>

  <% end %>

</div>

app/views/users/new.html.erb
<div align="center"><h2>Create New User</h2></div><br><br>

<div class="container">
<%= form_for @user do |f| %>
<% if !flash[:errors].nil? %>
    <% flash[:errors].each do |message| %>
      <li><%= message %></li>
    <% end %>
<% end %>

<div class="input-field">
    <%= f.label :username %>
    <%= f.text_field :username, required: true %><br>
</div>

<div class="input-field">
    <%= f.label :password %>
    <%= f.password_field :password, required: true %><br>
</div>

<div class="input-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true %><br>
</div>

<div class="input-field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %><br>
</div>

<div class="input-field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
</div>

<div class="input-field">
    <%= f.label :street_address %>
    <%= f.text_field :street_address %><br>
</div>

<div class="input-field">
    <%= f.label :city %>
    <%= f.text_field :city %><br>
</div>

<div class="input-field">
    <%= f.label :state %>
    <%= f.text_field :state %><br>
</div>

<div class="input-field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %><br>
</div>

<div class="input-field">
    <%= f.label :email %>
    <%= f.text_field :email, required: true %><br>
</div>

<div class="input-field">
    <%= f.label :phone %>
    <%= f.text_field :phone, required: true %><br><br>
</div>

<center><%= f.submit "Create Account", class: "waves-effect waves-light btn"%><br><br>
<% end %>

</div>

app/views/users/posts.html.erb
<!--
<div class="row">

<% @posts.each do |post| %>

  <div class="posts">
    <a href="<%= post_path(post) %>">
    <%= post.id %>
    <%= post.title %>
    </a>

    <p> Responses: <%= post.responses.count %></p>
    <%= button_to "Delete Post", post_path(post), method: 'delete', class: "waves-effect waves-light btn" %>
    <br>
  </div>


<% end %>
<br>

</div> -->


<div class="row">
<% @posts.each do |post| %>

<div class="col m4">
<div class="card">
  <div class="card-image">
    <img src="https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg">
    <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">+</i></a> -->
  </div>
      <a href="<%= post_path(post) %>">
      <%= post.id %>
      <%= post.title %>
      </a>
  <div class="card-action">
    <div class="row">
    <div class="waves-effect waves-light btn red" style="float:right">
        <%= button_to "Delete Post", post_path(post), method: 'delete'%>
    </div>

    <% if post.responses.count == 0 %>
        <div class="waves-effect waves-light btn green" style="float:left">
            <%= button_to "No Responses Yet", post_path(post), method: 'get'%>
        </div>
    <% else %>
        <div class="waves-effect waves-light btn green" style="float:left">
            <%= button_to "View Responses (#{post.responses.count})", post_path(post), method: 'get'%>
        </div>
    <% end %>


    </div>
  </div>

</div>
</div>

<% end %>
</div>

app/views/users/show.html.erb
<div class="container">

<div class="row">



<div class="col s3">
  <h2>Profile</h2>
<% if current_user == @user.id %>
    Name: <%= @user.first_name %> <%= @user.last_name %><br>
    Registered email: <%= @user.email %><br>
    Member Since: <%= @user.created_at.month %>/<%= @user.created_at.year %><br><br>
    <%= button_to "Edit Profile", edit_user_path, method: 'get', class: "waves-effect waves-light btn" %><br><br>
<% end%>
</div>

<div class="col s9 push-s2">
  <br>
  <br>
  <br>
  <%= render "user_table" %>
  <br>
  <div style="float:right"> <%= button_to "Create Post", new_post_path, method: 'get', class: "waves-effect waves-light btn" %>   </div>


</div>
</div>
</div>