config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: "welcome#index", as: 'root'
  get '/users/login', to: "user_sessions#new", as: 'users_login'
  post '/users/login', to: "user_sessions#create"
  get '/vendors/login', to: 'vendor_sessions#new', as: 'vendors_login'
  post '/vendors/login', to: 'vendor_sessions#create'
  delete '/users/logout', to: 'user_sessions#destroy', as: 'users_logout'
  delete '/vendors/logout', to: 'vendor_sessions#destroy', as: 'vendors_logout'
  get '/vendors/:id/gigs', to: 'vendors#gigs', as: 'vendor_gigs'
  get '/vendors/:id/responses', to: 'vendors#responses', as: 'vendor_responses'

  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/vendors/:id/reviews', to: 'vendors#reviews', as: 'vendor_reviews'
  get '/posts/:id/messages', to: 'posts#messages', as: 'message'
  get '/index', to: 'searches#index', as: 'index_search'
  get '/search', to: 'searches#new', as: 'new_search'
  get '/show_search', to: 'searches#show_search', as: 'show_searches'
  post '/search', to: 'searches#create'
  post '/vendors/:id/add_service', to: 'vendors#add_service', as: 'add_service'

  get '/search', to: 'searches#new', as: "search_new"

  resources :responses, only: [:new,:create,:destroy]
  resources :users, :vendors, :posts, :reviews
  resources :messages, only: [:create]
  resources :searches, only: [:show, :show_search, :create]
end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  company_name    :string
#  phone           :string
#  email           :string
#  city            :string
#  state           :string
#  zip_code        :integer
#  street_address  :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Vendor < ApplicationRecord
  has_secure_password

  has_many :vendor_services
  has_many :services, through: :vendor_services
  has_many :responses
  has_many :reviews, through: :responses

  # before_validation :password_criteria
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "is invalid" }
  validates :username, uniqueness: true

  # def password_criteria
  #   errors.add(:password, "is invalid") if !(password.length > 6 && password =~ /[A-Z]/ && password =~ /[0-9]/ && password != username)
  # end


  def score
    return 0 if self.reviews.empty?
    1.0 * self.reviews.map(&:score).inject(:+) / (self.reviews.count)
  end


end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_action :vendor_logged_in?, :vendor_exists?, only: [:edit, :gigs, :reviews, :responses]

  def index
    @vendors = Vendor.all
  end


  def new
    @vendor = Vendor.new
  end

  def add_service
    # byebug
    @service = Service.find_by(name: params[:service])
    @post = Post.find(params[:post])
    @vendor = Vendor.find(current_vendor)
    @vendor.services << @service
    redirect_to posts_path
  end


  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      session[:vendor_id] = @vendor.id
      redirect_to vendor_path(@vendor)
    else
      redirect_to new_vendor_path
    end
  end


  def show
    @vendor = Vendor.find(params[:id])
    @services = Vendor.find(params[:id]).services

    if current_vendor == params[:id].to_i
      @max_display = 2
      @gigs = @vendor.responses.select(&:accepted).map(&:post)[0..@max_display]
      all_services = Vendor.find(current_vendor).services.map {|service| service.id}
      @posts = Post.all.select do |post|
        all_services.include?(post.service_id) && !post.responses.map(&:vendor_id).include?(current_vendor)
      end[0..@max_display]
      render :show
    else
      render :public_show
    end
  end

  def edit
    @vendor = Vendor.find(current_vendor)
    @services = Service.all.sort_by(&:name)
  end


  def update
    @vendor = Vendor.find(current_vendor)
    @vendor.update(vendor_params)
    @vendor.services = []
    if !params[:vendor][:services].nil?
      params[:vendor][:services].each do |service|
        @vendor.services << Service.find(service)
      end
    end
    @vendor.save
    redirect_to vendor_path(@vendor)
  end

  def reviews
    @vendor = Vendor.find(current_vendor)
  end

  def gigs
    @vendor = Vendor.find(current_vendor)
    @gigs = @vendor.responses.select(&:accepted).map(&:post)
  end

  def responses
    @responses = Vendor.find(current_vendor).responses.select(&:post)
  end


  private

  def vendor_params
    params.require(:vendor).permit(:username, :password, :password_confirmation, :company_name, :street_address, :city, :state, :zip_code, :email, :phone)
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_mini_table.html.erb
<table>
<thead>
  <tr>
      <th>User</th>
      <th>Title</th>
      <th>Due On</th>
  </tr>
</thead>
<tbody>
  <% @gigs.each do |gig| %>
  <!-- <p>User: <%= gig.user.username %></p>
  <p>Title: <%= gig.title %></p>
  <p>Description <%= gig.description %></p> -->
    <tr>
      <td> <%= gig.user.username %> </td>
      <td> <%= link_to "#{gig.title}", message_path(gig), method: 'get' %> </td>
      <td> <%= gig.created_at%> </td>
    </tr>
  <!-- add button that allows user and vendor to go to show page of message controller and then allows to message -->
  <% end %>

</tbody>
</table>
<% if !@gigs.empty? %>
<div class="waves-effect waves-light btn", style="float:right"> <%= button_to "All Active Gigs", vendor_gigs_path(@vendor), method: 'get' %> </div>
<% else %>
<div class="waves-effect waves-light btn", style="float:right"> No Active Gigs </div>
<% end %>
<br>
<br>

<table>
<thead>
  <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price Quote</th>
  </tr>
</thead>
<tbody>
    <% @vendor.responses.each do |response| %>
    <tr>
      <td> <%= response.post.title %> </td>
    <td><%= truncate response.post.description, length:15, separator:/\w/, omission: "..."%></td>
    <td><%= response.price_quote %></td>
      </tr>
      <%end %>
</tbody>
</table>
<% if !@vendor.responses.empty? %>
<div class="waves-effect waves-light btn", style="float:right"> <%= button_to "Awaiting Response", vendor_responses_path(@vendor), method: 'get' %> </div>
<% else %>
<div class="waves-effect waves-light btn", style="float:right"> No Responses </div>
<% end %>


<br>
<br>
  <table>
  <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price Range</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate post.description, length:15, separator:/\w/, omission: "..." %></td>
        <td>$ <%= post.min_price%> - $ <%= post.max_price%></td>
      </tr>

    <% end %>
  </tbody>
  </table>

  <% if !@posts.empty? %>
  <div class="waves-effect waves-light btn" style="float:right"> <%= button_to "More Gigs Available", posts_path, method: 'get' %> </div>
  <% else %>
  <div class="waves-effect waves-light btn", style="float:right"> No Gigs Available </div>
  <% end %>

app/views/vendors/_public_view.html.erb
<div style="text-align:center">
<h3><%= @vendor.company_name.capitalize %></h3>
Member Since: <%= @vendor.created_at.month %> / <%= @vendor.created_at.year %> <br><br>
</div>
<ul class="collection with-header">
  <li class="collection-header"><b>Services Offered:</b></li>
  <% @services.each do |service| %>
  <li class="collection-item"> <%= service.name %> </li>
<% end %>
<% if current_vendor == @vendor.id%>  <a href="<%=edit_vendor_path%>" class="collection-item"> Add/Remove Services </a> <% end %>
</ul>

app/views/vendors/edit.html.erb
<div class="container">

<br>

<%= form_for @vendor do |f| %>
<div class="input-field">
<%= f.label :company_name%>
<%= f.text_field :company_name %>
</div>
<div class="input-field">
<%= f.label :phone %>
<%= f.text_field :phone %>
</div>
<div class="input-field">
<%= f.label :email %>
<%= f.text_field :email %>
</div>

<%= f.label :services %>
<br>
<%= f.collection_check_boxes(:services, @services, :id,:name, :include_hidden => false) do |t| %>
<br>
<%= t.check_box(checked: @vendor.services.map(&:id).include?(t.value)) %> <%= t.label %>
<% end %>
<br>
<br>
<div class="waves-effect waves-light btn"><%= f.submit %> <div>
<%= button_to "Cancel", vendor_path(current_vendor), method: 'get', class: "waves-effect waves-light btn" %>
<% end %>

</div>

app/views/vendors/gigs.html.erb
<div class="container">


<h4>Active Gigs</h4>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Order Date</th>
      <th>Due On</th>
      <th>Price</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>

<% @gigs.each do |gig| %>
<!-- <p>User: <%= gig.user.username %></p>
<p>Title: <%= gig.title %></p>
<p>Description <%= gig.description %></p> -->
  <tr>
    <td> <%= gig.user.username %> </td>
    <td> <%= link_to "#{gig.title}", message_path(gig), method: 'get' %> </td>
    <td> <%= gig.created_at.to_date%> </td>
    <td> <%= gig.created_at.to_date%> </td>
    <td> <%= gig.responses.select(&:accepted).first.price_quote %></td>
    <td> In Progress </td>

  </tr>
<!-- add button that allows user and vendor to go to show page of message controller and then allows to message -->
<% end %>
  </tbody>
</table>

</div>

app/views/vendors/index.html.erb
<div class="container">

<h4>Vendors</h4>
<table class="striped">
<tr>
    <th>Company</th>
    <th>Rating</th>
</tr>




<% @vendors.each do |vendor| %>
<tr>


<td><%= link_to "#{vendor.company_name}", vendor_path(vendor.id), method: 'get'  %> </td>
<td> <%= vendor.score %> </td>
</tr>
<% end %>

</table>
</div>

app/views/vendors/new.html.erb
<div class="container">
<div align="center"><h2>Create New Vendor</h2></div><br>

<%= form_for @vendor do |f| %>
<div class="input-field">
<%= f.label :username %>
<%= f.text_field :username %>
</div>
<div class="input-field">
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div class="input-field">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<div class="input-field">
<%= f.label :company_name %>
<%= f.text_field :company_name %>
</div>
<div class="input-field">
<%= f.label :email %>
<%= f.text_field :email %>
</div>
<br>
<br>
<div class="waves-effect waves-light btn"> <%= f.submit "Create Account"%> </div>
<% end %>

</div>

app/views/vendors/public_show.html.erb
<div class="container">
  <br>

  <%= render "public_view" %>

</div>

app/views/vendors/responses.html.erb
<div class="row">
<% @responses.each do |response| %>
<div class="col m4">
<div class="card">
  <div class="card-image">
    <img src="https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg">
    <span class="card-title"><%= response.post.title %></span>
    <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">+</i></a> -->
  </div>
  <div class="card-content">
    <p><%= response.post.description%></p>
  </div>
  <div class="card-action">
    <div class="row">
    Price Quote: $<%= response.price_quote %>
    <div class="waves-effect waves-light btn red" style="float:right">
        <%= button_to "Delete", response_path(response), method:'delete'%>
    </div>
    </div>
  </div>

</div>
</div>

<% end %>
</div>

app/views/vendors/reviews.html.erb
<%= @vendor.reviews.each do |review| %>
<%= review %>
<% end %>

app/views/vendors/show.html.erb
<div class="container">

<div class="row">

      <div class="col s3">
        <%= render "public_view" %>
      </div>

      <div class="col s9 push-s2">
        <br>
        <br>
        <br>
        <%= render "mini_table" %>
      </div>

</div>
</div>