config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: "welcome#index", as: 'root'
  get '/users/login', to: "user_sessions#new", as: 'users_login'
  post '/users/login', to: "user_sessions#create"
  get '/vendors/login', to: 'vendor_sessions#new', as: 'vendors_login'
  post '/vendors/login', to: 'vendor_sessions#create'
  delete '/users/logout', to: 'user_sessions#destroy', as: 'users_logout'
  delete '/vendors/logout', to: 'vendor_sessions#destroy', as: 'vendors_logout'
  get '/vendors/:id/gigs', to: 'vendors#gigs', as: 'vendor_gigs'
  get '/vendors/:id/responses', to: 'vendors#responses', as: 'vendor_responses'

  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/vendors/:id/reviews', to: 'vendors#reviews', as: 'vendor_reviews'
  get '/posts/:id/messages', to: 'posts#messages', as: 'message'
  get '/index', to: 'searches#index', as: 'index_search'
  get '/search', to: 'searches#new', as: 'new_search'
  get '/show_search', to: 'searches#show_search', as: 'show_searches'
  post '/search', to: 'searches#create'
  post '/vendors/:id/add_service', to: 'vendors#add_service', as: 'add_service'

  get '/search', to: 'searches#new', as: "search_new"

  resources :responses, only: [:new,:create,:destroy]
  resources :users, :vendors, :posts, :reviews
  resources :messages, only: [:create]
  resources :searches, only: [:show, :show_search, :create]
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


  # def index
  #   @services = Service.new
  # end

  def new
    @services = Service.new
    @all_services = Service.all.sort_by(&:name)
  end

  #params[:service] gives services id
  #params[:max_price] gives max price
  #params[:min_price] gives min price


  def create
    if current_vendor
    @vendor = Vendor.find(session[:vendor_id])
    end

    @services = params[:service][:id].map {|service|
    Service.find(params[:service][:id])}.first

    @services_id = params[:service][:id].map(&:to_i)
    @max_price = params[:max_price].to_i
    @min_price = params[:min_price].to_i

    @posts = Post.all.select do |post|
      @services_id.include?(post.service_id) && post.max_price <= @max_price && post.min_price >= @min_price
    end
    render "show_search"
  end

  def show_search
    #this method should show the specific post a vendor clicks on from the search results and allows him to respond and/or add that service to his account
  end

  def show
  end




end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<div class="container">



<!-- take in search and submit to -->

<h3>Search By Category and/or Price Range</h3>
<%= form_for @services, :url => new_search_path do |f| %>

<br>
<%= f.label :services %>
<br>
<%= f.collection_check_boxes(:id, @all_services, :id,:name, :include_hidden => false) %>
<br>

<%= form_tag new_search_path do %>
<br>
<h4>Price Range</h4>
<br>
<%= label_tag :min_price %>
<%= number_field_tag :min_price %>
<%= label_tag :max_price %>
<%= number_field_tag :max_price %>


<div class="waves-effect waves-light btn"><%= f.submit "Search" %> <div>
<% end %>
<% end %>

</div>

app/views/searches/show_search.html.erb
<div class="row"
<center><h2>Your Results</h2>
  <br>
<% @posts.each do |post| %>
<div class="col m4">
<div class="card">
  <div class="card-image">
    <img
      src="https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg">
      <span class="card-title"><%= post.title %></span>
    </div>
    <div class="card-content">
<p> Description: <%= post.description %></p>
</div>
<div class="card-action">
  <div class="row">
<p> Min Price: <%= post.min_price %></p>
<p> Max Price: <%= post.max_price %></p>
  <div class="waves-effect waves-light btn red" style="float:right">

 <!-- add_service_to_vendor(@vendor, Service.find(post.service_id).name, post ) -->
<% if vendor_has_service?(@vendor,Service.find(post.service_id)) %>
<%= link_to "See this post", posts_path %>
<% else %>
<% @service = Service.find(post.service_id).name %>

<%= form_tag(add_service_path(current_vendor)) do %>
<%= hidden_field_tag :service, @service %>
<%= hidden_field_tag :post, post.id %>
<%= submit_tag "Add #{@service} service to your account" %>
<% end %>
<% end %>


</div>
</div>
</div>

</div>
</div>
<% end %>
</div>