config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: "welcome#index", as: 'root'
  get '/users/login', to: "user_sessions#new", as: 'users_login'
  post '/users/login', to: "user_sessions#create"
  get '/vendors/login', to: 'vendor_sessions#new', as: 'vendors_login'
  post '/vendors/login', to: 'vendor_sessions#create'
  delete '/users/logout', to: 'user_sessions#destroy', as: 'users_logout'
  delete '/vendors/logout', to: 'vendor_sessions#destroy', as: 'vendors_logout'
  get '/vendors/:id/gigs', to: 'vendors#gigs', as: 'vendor_gigs'
  get '/vendors/:id/responses', to: 'vendors#responses', as: 'vendor_responses'

  get '/users/:id/posts', to: 'users#posts', as: 'user_posts'
  get '/vendors/:id/reviews', to: 'vendors#reviews', as: 'vendor_reviews'
  get '/posts/:id/messages', to: 'posts#messages', as: 'message'
  get '/index', to: 'searches#index', as: 'index_search'
  get '/search', to: 'searches#new', as: 'new_search'
  get '/show_search', to: 'searches#show_search', as: 'show_searches'
  post '/search', to: 'searches#create'
  post '/vendors/:id/add_service', to: 'vendors#add_service', as: 'add_service'

  get '/search', to: 'searches#new', as: "search_new"

  resources :responses, only: [:new,:create,:destroy]
  resources :users, :vendors, :posts, :reviews
  resources :messages, only: [:create]
  resources :searches, only: [:show, :show_search, :create]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  service_id  :integer
#  user_id     :integer
#  title       :string
#  description :string
#  min_price   :float
#  max_price   :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord

  belongs_to :user
  belongs_to :service
  has_many :responses

  before_validation :check_price

  def check_price
    errors.add(:max_price, 'can not be less than min price') if min_price > max_price
  end

  def order_responses_by_score
    self.responses.sort_by(&:score).reverse
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_logged_in?, only: [:new,:create,:destroy,:show]
  before_action :vendor_logged_in?, only: [:index]
  before_action :users_posts?, only: [:show]


  def index
    #Vendor sees all applicable gigs to him, but not the ones he already responded to
    all_services = Vendor.find(current_vendor).services.map {|service| service.id}
    @posts = Post.all.select do |post|
      all_services.include?(post.service_id) && !post.responses.map(&:vendor_id).include?(current_vendor)
    end
  end

  def new
    @post = Post.new
  end

  def show
    #If the user Accepted a response than he can only view that response
    #User can see his specific post and all responses to that post if not accepted response
    @post = Post.find(params[:id])
    @responses = accepted_responses
  end

  def create
    @post = Post.new(post_params)
    User.find(session[:user_id]).posts << @post
    redirect_to user_posts_path(current_user)
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to user_posts_path(current_user)
  end

  def messages
    @post = Post.find(params[:id])
    @response = @post.responses.select(&:accepted).first
    @message = Message.new
  end

  private
  def post_params
    params.require(:post).permit(:service_id, :title, :description, :min_price, :max_price)
  end

  def accepted_responses
    if !@post.responses.select(&:accepted).empty?
      @post.responses.select(&:accepted)
    else
      @post.order_responses_by_score
    end
  end



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="row">
<% @posts.each do |post| %>

<div class="col m4">
<div class="card">
  <div class="card-image">
    <img src="https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg">
    <span class="card-title"><%= post.title %></span>
    <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">+</i></a> -->
  </div>
  <div class="card-content">
    <p><%= post.description%></p>
  </div>
  <div class="card-action">
    <div class="row">
    Price Range: $ <%= post.min_price%> - $ <%= post.max_price%>
    <div class="waves-effect waves-light btn red" style="float:right">
        <%= button_to "Respond", new_response_path, params: {'post_id' => post.id}, method:'get'%>
    </div>
    </div>
  </div>

</div>
</div>

<% end %>
</div>







<!-- <% @posts.each do |post| %>
Descrption: <%= post.description %> <br>
Min Price: <%= post.min_price %> <br>
Max Price: <%= post.max_price %> <br>
<br>
<%= button_to "Respond", new_response_path, params: {'post_id' => post.id}, method:'get'%>
<br>
<% end %>
<br> -->

app/views/posts/messages.html.erb
<div class="container">


<h3>Posted By: <%= @post.user.username %></h3>
<h4>Title: <%= @post.title %></h4>
<h4>Description: <%= @post.description %></h4>
<br>

<div class="card-panel">
      <span class="grey-text text-darken-2">

<% @response.messages.each do |msg| %>
<p><%= message_owner(msg) %>: <%= msg.comment %></p>
<% end %>
</span>
  </div>

<%= form_for @message  do |f| %>
<%= f.hidden_field :response_id, value: @response.id  %>
<%= f.label :comment %>
<%= f.text_area :comment %>
<br>
<%= f.submit "Post Message" %>
<% end %>
<br>

<%= button_to "Return to Post", post_path(@post), method: 'get' %>

</div>

app/views/posts/new.html.erb
<h2 align="center">Create New Post:</h2><br><br>

<div class="container">
  <%= form_for @post do |f| %>


    <%= f.label :service_id%>
    <div class="input-field col s12 m6">
    <%= f.select :service_id, Service.all.sort_by {|p| p.name}.collect {|p| [ p.name, p.id ] }%>
  </div><br>

  <div class="input-field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="input-field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="input-field">
    <%= f.label :min_price %>
    <%= f.number_field :min_price %>
  </div>

  <div class="input-field">
    <%= f.label :max_price %>
    <%= f.number_field :max_price %>
  </div><br>



  <%= f.submit "Submit Post", class: "waves-effect waves-light btn" %>
  <% end %>

  <br>
  <%= button_to "Cancel", user_path(current_user), method: 'get', class: "waves-effect waves-light btn" %>


</div>

app/views/posts/show.html.erb
<br>
<%= button_to "All Posts", user_posts_path(current_user), method: 'get', class: "waves-effect waves-light btn"%>

<div class="container">

  <div>
    <h3><%= @post.title %></h3>
    <h4><%= @post.description %></h4>
  </div><br><br>

<div class="responses">


    <% @responses.each do |response| %>
    Title: <%= response.title %> <br>
    Desc: <%= response.description %> <br>
    Price: <%= response.price_quote %> <br>
    Vendor Rating: <%= response.vendor.score %> <br>
    <% if !response.accepted %>
    <%= button_to "Accept", response_path(response), method: 'delete', params: {accept:true}, class: "waves-effect waves-light btn green" %>
    <%= button_to "Decline", response_path(response) , method: 'delete', class: "waves-effect waves-light btn red" %>
    <% elsif response.review.nil? %>
    <%= button_to "Rate Vendor!", new_review_path, method: 'get', params: {response_id: response.id}, class: "waves-effect waves-light btn" %>
    <% else %>
    Your Review: <%= response.review.score %>
    <% end %>
    <% if response.accepted %>
    <br>
     <%= button_to "Go To Messages", message_path(@post), method: 'get', class: "waves-effect waves-light btn" %>
    <% end  %>
    <!-- Internal use only!!  -->
    <br>
    <!-- <%= response.score %> -->
    <% end %>

</div>
</div>